// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranHoangViet_231230961_de01.Models;

#nullable disable

namespace TranHoangViet_231230961_de01.Migrations
{
    [DbContext(typeof(thvComputerText))]
    partial class thvComputerTextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TranHoangViet_231230961_de01.Models.thvComputers", b =>
                {
                    b.Property<string>("thvComputersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("thvComImgae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("thvComPrice")
                        .HasColumnType("int");

                    b.Property<bool>("thvComStatus")
                        .HasColumnType("bit");

                    b.Property<string>("thvComputersName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("thvComputersId");

                    b.ToTable("thvComputers");
                });
#pragma warning restore 612, 618
        }
    }
}
